### ISSUE TITLE
Spark Cluster - BlockManagerId local class incompatible: stream classdesc serialVersionUID

### ISSUE THREAD

**Issue by tsindot** [NFLabs/zeppelin#292]
First thanks for all the time an effort on the project, it is a great tool. Second I apologize in advance for the length of this post.

Environment:
* JDK 8, version 1.8.0_25-b17
* Macbook Pro (OS X 10.9.5)
* Spark 1.1.1
* Zeppelin - git clone of master and built with:
    * ```mvn install -DskipTests -Dspark.version=1.1.1 -Dhadoop.version=2.4.0```

I’m going through the [tutorial](http://zeppelin-project.org/docs/tutorial/tutorial.html) and when I run it in a standalone mode, i.e. no separate Spark Master / Cluster, everything seem works fine. 

However, if I startup a standalone spark cluster as follows:

* Master:  ```$SPARK_HOME/sbin/start-master.sh```
* Worker1: ```$SPARK_HOME//bin/spark-class org.apache.spark.deploy.worker.Worker spark://radtech.io:7077 --webui-port 8081 --cores 2 --memory 1G```
* Worker2: ```$SPARK_HOME//bin/spark-class org.apache.spark.deploy.worker.Worker spark://radtech.io:7077 --webui-port 8082 --cores 2 --memory 1G``

Then modify the conf/zeppelin-enf.conf to attach to the cluster:
```
#!/bin/bash

# export JAVA_HOME=
 export MASTER=spark://radtech.io:7077 # spark master

# export ZEPPELIN_JAVA_OPTS      # additional jvm options. for example, export ZEPPELIN_JAVA_OPTS="-Dspark.executor.memory=8g -Dspark.cores.max=16"
# export ZEPPELIN_MEM            # zeppelin jvm mem options Defualt -Xmx1024m -XX:MaxPermSize=512m

# export ZEPPELIN_CONF_DIR       # Alternate zeppelin conf dir. Default is ${HBASE_HOME}/conf.
# export ZEPPELIN_LOG_DIR        # Where log files are stored.  PWD by default.
# export ZEPPELIN_PID_DIR        # The pid files are stored. /tmp by default.
# export ZEPPELIN_NOTEBOOK_DIR   # Where notebook saved
# export ZEPPELIN_IDENT_STRING   # A string representing this instance of zeppelin. $USER by default
# export ZEPPELIN_NICENESS       # The scheduling priority for daemons. Defaults to 0.
```

 I start to experience problems, specifically ```serialVersionUID``` incompatibility  issues.  It appears that there may be 2 instances of ```org.apache.spark.storage.BlockManagerId``` based on this exception below.

Now when I execute this example from the tutorial, 
```
val bankText = sc.textFile("/Users/work/zeppelin_test_data/bank/bank-full.csv")

case class Bank(age:Integer, job:String, marital : String, education : String, balance : Integer)

val bank = bankText.map(s=>s.split(";")).filter(s=>s(0)!="\"age\"").map(
    s=>Bank(s(0).toInt, 
            s(1).replaceAll("\"", ""),
            s(2).replaceAll("\"", ""),
            s(3).replaceAll("\"", ""),
            s(5).replaceAll("\"", "").toInt
        )
)

bank.registerTempTable("bank”)
```
I see the following in the log after it is "Finished" in the UI:

```
 INFO [2015-01-20 13:12:06,085] ({sparkDriver-akka.actor.default-dispatcher-3} Slf4jLogger.scala[applyOrElse]:80) - Slf4jLogger started
 INFO [2015-01-20 13:12:06,180] ({sparkDriver-akka.actor.default-dispatcher-2} Slf4jLogger.scala[apply$mcV$sp]:74) - Starting remoting
 INFO [2015-01-20 13:12:06,609] ({sparkDriver-akka.actor.default-dispatcher-3} Slf4jLogger.scala[apply$mcV$sp]:74) - Remoting started; listening on addresses :[akka.tcp://sparkDriver@192.168.1.3:50413]
 INFO [2015-01-20 13:12:06,614] ({sparkDriver-akka.actor.default-dispatcher-5} Slf4jLogger.scala[apply$mcV$sp]:74) - Remoting now listens on addresses: [akka.tcp://sparkDriver@192.168.1.3:50413]
 INFO [2015-01-20 13:12:06,627] ({Thread-25} Logging.scala[logInfo]:59) - Successfully started service 'sparkDriver' on port 50413.
 INFO [2015-01-20 13:12:06,660] ({Thread-25} Logging.scala[logInfo]:59) - Registering MapOutputTracker
 INFO [2015-01-20 13:12:06,675] ({Thread-25} Logging.scala[logInfo]:59) - Registering BlockManagerMaster
 INFO [2015-01-20 13:12:06,714] ({Thread-25} Logging.scala[logInfo]:59) - Created local directory at /var/folders/kv/t9dpl73124l4hbk5kbxjl_y40000gn/T/spark-local-20150120131206-ae57
 INFO [2015-01-20 13:12:06,946] ({Thread-25} Logging.scala[logInfo]:59) - Successfully started service 'Connection manager for block manager' on port 50414.
 INFO [2015-01-20 13:12:06,949] ({Thread-25} Logging.scala[logInfo]:59) - Bound socket to port 50414 with id = ConnectionManagerId(192.168.1.3,50414)
 INFO [2015-01-20 13:12:06,954] ({Thread-25} Logging.scala[logInfo]:59) - MemoryStore started with capacity 491.7 MB
 INFO [2015-01-20 13:12:06,964] ({Thread-25} Logging.scala[logInfo]:59) - Trying to register BlockManager
 INFO [2015-01-20 13:12:06,969] ({sparkDriver-akka.actor.default-dispatcher-3} Logging.scala[logInfo]:59) - Registering block manager 192.168.1.3:50414 with 491.7 MB RAM, BlockManagerId(<driver>, 192.168.1.3, 50414, 0)
 INFO [2015-01-20 13:12:06,973] ({Thread-25} Logging.scala[logInfo]:59) - Registered BlockManager
 INFO [2015-01-20 13:12:07,009] ({Thread-25} Logging.scala[logInfo]:59) - HTTP File server directory is /var/folders/kv/t9dpl73124l4hbk5kbxjl_y40000gn/T/spark-aacd8b91-610e-452c-976b-19b765dffa9d
 INFO [2015-01-20 13:12:07,009] ({Thread-25} Logging.scala[logInfo]:59) - Starting HTTP Server
 INFO [2015-01-20 13:12:07,011] ({Thread-25} Server.java[doStart]:272) - jetty-8.1.14.v20131031
 INFO [2015-01-20 13:12:07,013] ({Thread-25} AbstractConnector.java[doStart]:338) - Started SocketConnector@0.0.0.0:50415
 INFO [2015-01-20 13:12:07,015] ({Thread-25} Logging.scala[logInfo]:59) - Successfully started service 'HTTP file server' on port 50415.
 INFO [2015-01-20 13:12:07,382] ({Thread-25} Server.java[doStart]:272) - jetty-8.1.14.v20131031
 INFO [2015-01-20 13:12:07,396] ({Thread-25} AbstractConnector.java[doStart]:338) - Started SelectChannelConnector@0.0.0.0:4040
 INFO [2015-01-20 13:12:07,398] ({Thread-25} Logging.scala[logInfo]:59) - Successfully started service 'SparkUI' on port 4040.
 INFO [2015-01-20 13:12:07,405] ({Thread-25} Logging.scala[logInfo]:59) - Started SparkUI at http://192.168.1.3:4040
 WARN [2015-01-20 13:12:07,697] ({Thread-25} NativeCodeLoader.java[<clinit>]:62) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
 INFO [2015-01-20 13:12:08,027] ({Thread-25} Logging.scala[logInfo]:59) - Created default pool default, schedulingMode: FIFO, minShare: 0, weight: 1
 INFO [2015-01-20 13:12:08,082] ({sparkDriver-akka.actor.default-dispatcher-3} Logging.scala[logInfo]:59) - Connecting to master spark://radtech.io:7077...
 INFO [2015-01-20 13:12:08,103] ({Thread-25} Logging.scala[logInfo]:59) - SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
 INFO [2015-01-20 13:12:08,774] ({sparkDriver-akka.actor.default-dispatcher-2} Logging.scala[logInfo]:59) - Connected to Spark cluster with app ID app-20150120131208-0001
 INFO [2015-01-20 13:12:08,778] ({sparkDriver-akka.actor.default-dispatcher-2} Logging.scala[logInfo]:59) - Executor added: app-20150120131208-0001/0 on worker-20150120125923-192.168.1.3-50327 (192.168.1.3:50327) with 2 cores
 INFO [2015-01-20 13:12:08,781] ({sparkDriver-akka.actor.default-dispatcher-2} Logging.scala[logInfo]:59) - Granted executor ID app-20150120131208-0001/0 on hostPort 192.168.1.3:50327 with 2 cores, 512.0 MB RAM
 INFO [2015-01-20 13:12:08,782] ({sparkDriver-akka.actor.default-dispatcher-2} Logging.scala[logInfo]:59) - Executor added: app-20150120131208-0001/1 on worker-20150120125930-192.168.1.3-50329 (192.168.1.3:50329) with 2 cores
 INFO [2015-01-20 13:12:08,783] ({sparkDriver-akka.actor.default-dispatcher-2} Logging.scala[logInfo]:59) - Granted executor ID app-20150120131208-0001/1 on hostPort 192.168.1.3:50329 with 2 cores, 512.0 MB RAM
 INFO [2015-01-20 13:12:08,804] ({sparkDriver-akka.actor.default-dispatcher-2} Logging.scala[logInfo]:59) - Executor updated: app-20150120131208-0001/0 is now LOADING
 INFO [2015-01-20 13:12:08,806] ({sparkDriver-akka.actor.default-dispatcher-2} Logging.scala[logInfo]:59) - Executor updated: app-20150120131208-0001/1 is now LOADING
 INFO [2015-01-20 13:12:10,988] ({sparkDriver-akka.actor.default-dispatcher-5} Logging.scala[logInfo]:59) - Executor updated: app-20150120131208-0001/0 is now RUNNING
 INFO [2015-01-20 13:12:11,153] ({sparkDriver-akka.actor.default-dispatcher-5} Logging.scala[logInfo]:59) - Executor updated: app-20150120131208-0001/1 is now RUNNING
 INFO [2015-01-20 13:12:15,957] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:16,459] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:16,960] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:17,461] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:17,858] ({pool-2-thread-2} Paragraph.java[jobRun]:182) - RUN : val bankText = sc.textFile("/Users/tnist/zeppelin_test_data/bank/bank-full.csv")

case class Bank(age:Integer, job:String, marital : String, education : String, balance : Integer)

val bank = bankText.map(s=>s.split(";")).filter(s=>s(0)!="\"age\"").map(
    s=>Bank(s(0).toInt,
            s(1).replaceAll("\"", ""),
            s(2).replaceAll("\"", ""),
            s(3).replaceAll("\"", ""),
            s(5).replaceAll("\"", "").toInt
        )
)

bank.registerTempTable("bank")
 INFO [2015-01-20 13:12:17,964] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:17,977] ({sparkDriver-akka.actor.default-dispatcher-14} Logging.scala[logInfo]:59) - Registered executor: Actor[akka.tcp://sparkExecutor@192.168.1.3:50420/user/Executor#-425896573] with ID 0
 INFO [2015-01-20 13:12:18,465] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:18,639] ({sparkDriver-akka.actor.default-dispatcher-17} Logging.scala[logInfo]:59) - Registered executor: Actor[akka.tcp://sparkExecutor@192.168.1.3:50426/user/Executor#-2008077853] with ID 1
 INFO [2015-01-20 13:12:18,966] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:18,977] ({pool-2-thread-2} Logging.scala[logInfo]:59) - ensureFreeSpace(159118) called with curMem=0, maxMem=515553361
 INFO [2015-01-20 13:12:18,986] ({pool-2-thread-2} Logging.scala[logInfo]:59) - Block broadcast_0 stored as values in memory (estimated size 155.4 KB, free 491.5 MB)
 INFO [2015-01-20 13:12:19,174] ({pool-2-thread-2} Logging.scala[logInfo]:59) - ensureFreeSpace(12633) called with curMem=159118, maxMem=515553361
 INFO [2015-01-20 13:12:19,179] ({pool-2-thread-2} Logging.scala[logInfo]:59) - Block broadcast_0_piece0 stored as bytes in memory (estimated size 12.3 KB, free 491.5 MB)
 INFO [2015-01-20 13:12:19,184] ({sparkDriver-akka.actor.default-dispatcher-15} Logging.scala[logInfo]:59) - Added broadcast_0_piece0 in memory on 192.168.1.3:50414 (size: 12.3 KB, free: 491.7 MB)
 INFO [2015-01-20 13:12:19,188] ({pool-2-thread-2} Logging.scala[logInfo]:59) - Updated info of block broadcast_0_piece0
 INFO [2015-01-20 13:12:19,467] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:19,968] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:20,469] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:20,971] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:21,473] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:21,974] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:22,476] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:22,978] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:23,480] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:23,980] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:24,484] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:24,985] ({Thread-25} NotebookServer.java[broadcast]:204) - SEND >> PROGRESS
 INFO [2015-01-20 13:12:25,006] ({pool-2-thread-2} NotebookServer.java[afterStatusChange]:456) - Job 20150120-124755_719929768 is finished
 INFO [2015-01-20 13:12:25,006] ({pool-2-thread-2} Note.java[persist]:262) - Persist note 2AE6RR7YA into /Users/tnist/projects/radtech.io/zeppelin/notebook/2AE6RR7YA/note.json
 INFO [2015-01-20 13:12:25,015] ({pool-2-thread-2} NotebookServer.java[broadcast]:204) - SEND >> NOTE
 INFO [2015-01-20 13:12:25,018] ({pool-2-thread-2} SchedulerFactory.java[jobFinished]:99) - Job paragraph_1421776075682_-56845921 finished by scheduler com.nflabs.zeppelin.spark.SparkInterpreter1551788863
ERROR [2015-01-20 13:12:51,607] ({sparkDriver-akka.actor.default-dispatcher-17} Slf4jLogger.scala[apply$mcV$sp]:66) - org.apache.spark.storage.BlockManagerId; local class incompatible: stream classdesc serialVersionUID = -7366074099953117729, local class serialVersionUID = 1677335532749418220
java.io.InvalidClassException: org.apache.spark.storage.BlockManagerId; local class incompatible: stream classdesc serialVersionUID = -7366074099953117729, local class serialVersionUID = 1677335532749418220
at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:621)
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
at akka.serialization.JavaSerializer$$anonfun$1.apply(Serializer.scala:136)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
at akka.serialization.JavaSerializer.fromBinary(Serializer.scala:136)
at akka.serialization.Serialization$$anonfun$deserialize$1.apply(Serialization.scala:104)
at scala.util.Try$.apply(Try.scala:161)
at akka.serialization.Serialization.deserialize(Serialization.scala:98)
at akka.remote.MessageSerializer$.deserialize(MessageSerializer.scala:23)
at akka.remote.DefaultMessageDispatcher.payload$lzycompute$1(Endpoint.scala:55)
at akka.remote.DefaultMessageDispatcher.payload$1(Endpoint.scala:55)
at akka.remote.DefaultMessageDispatcher.dispatch(Endpoint.scala:73)
at akka.remote.EndpointReader$$anonfun$receive$2.applyOrElse(Endpoint.scala:764)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
at akka.actor.ActorCell.invoke(ActorCell.scala:456)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
at akka.dispatch.Mailbox.run(Mailbox.scala:219)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
ERROR [2015-01-20 13:12:51,990] ({sparkDriver-akka.actor.default-dispatcher-14} Slf4jLogger.scala[apply$mcV$sp]:66) - org.apache.spark.storage.BlockManagerId; local class incompatible: stream classdesc serialVersionUID = -7366074099953117729, local class serialVersionUID = 1677335532749418220
java.io.InvalidClassException: org.apache.spark.storage.BlockManagerId; local class incompatible: stream classdesc serialVersionUID = -7366074099953117729, local class serialVersionUID = 1677335532749418220
...
```
From that point on the system is pretty much useless until restarted.  Seems like I’m missing something in the configuration here that needs to be set for this to work but it is not obvious to me what it is.

Any guidance on configuration for Zeppelin in Spark Standalone Cluster would be appreciated or is this a bigger issue?  TIA for the assistance.  

-Todd

**Comment by Leemoonsoo** [comment]
Hi Todd,

I'm not sure why, but could you make sure you have a single version of spark related jar under interpreter/spark directory?
for example mine have only 1.1.1 related jars.

```
NFLabss-MacBook-Air-2:zeppelin moon$ ls interpreter/spark/spark-*
interpreter/spark/spark-bagel_2.10-1.1.1.jar			interpreter/spark/spark-repl_2.10-1.1.1.jar
interpreter/spark/spark-catalyst_2.10-1.1.1.jar			interpreter/spark/spark-sql_2.10-1.1.1.jar
interpreter/spark/spark-core_2.10-1.1.1.jar			interpreter/spark/spark-streaming-twitter_2.10-1.1.1.jar
interpreter/spark/spark-hive_2.10-1.1.1.jar			interpreter/spark/spark-streaming_2.10-1.1.1.jar
interpreter/spark/spark-mllib_2.10-1.1.1.jar
```

Another option is, you can copy spark jars from your spark installation to interpreter/spark directory for replacing them.
There were some discussion about dependency. #272  This thread might help you understand how Zeppelin loads spark dependencies at the moment.

**Comment by tsindot** [comment]
After doing some additional testing yesterday I found the problem, it was in fact self inflicted :(  I had upgraded to spark-1.1.1-hadoop2.4 to test it quickly.  Usually I create a link to symbolic link, ```ln -s /usr/local/spark-1.1.1-hadoop2.4 /usr/local/spark```.  I did not do that but had an ```$SPARK_HOME``` set to ```/usr/local/spark``` which was linked to ```spark-1.1.0-hadoop2.4``` thus the error.

I believe it is ok to close this one as I do not see it being related in anyway to #272. 

Thanks for the help and sorry for the noise.

- Todd
