### ISSUE TITLE
Error when running the tutorial

### ISSUE THREAD

**Issue by stevenbeeckman** [NFLabs/zeppelin#326]
Hi,

I am really happy to have discovered Zeppelin! 

I was following the tutorial and ran into a StackOverflowError when doing the first `%sql` commands.

```bash
4452- INFO [2015-02-07 00:21:07,962] ({pool-2-thread-3} NotebookServer.java[broadcast]:205) - SEND >> NOTE
4453- INFO [2015-02-07 00:21:08,002] ({pool-2-thread-3} Paragraph.java[jobRun]:165) - run paragraph 20150207-001205_31691915 using sql com.nflabs.zeppelin.interpreter.LazyOpenInterpreter@6734a
4454- INFO [2015-02-07 00:21:08,006] ({pool-2-thread-3} Paragraph.java[jobRun]:183) - RUN : select age, count(1) from bank where age < 30 group by age order by age
4455- INFO [2015-02-07 00:21:08,010] ({Thread-65} NotebookServer.java[broadcast]:205) - SEND >> PROGRESS
4456-ERROR [2015-02-07 00:21:08,038] ({pool-2-thread-3} Job.java[run]:164) - Job failed
4457:java.lang.StackOverflowError
4458-	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
4459-	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
4460-	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
4461-	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
4462-	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
```
Did you ever run into these?

**Comment by swkimme** [comment]
Hi Steven.

Tutorial codes works well for me,
What Spark version are you using? And what command did you used to build Zeppelin?

And would you try some simpler codes to examine it works?

plz try
sc.parallelize(0 to 100).map(x => (x, x*2)).registerTempTable("test")

%sql select * from test
