### ISSUE TITLE
Json4s class loading issue

### ISSUE THREAD

**Issue by swkimme** [NFLabs/zeppelin#336]
PredictionIO(https://github.com/PredictionIO/PredictionIO) team wants to integrate Zeppelin to PredictionIO. I think the PredictionIO + Zeppelin will be a great combination and I'm helping integration, 

During the work I've found some important code is failing due to class loading issue. 
following code is failing on Zeppelin, runnable in Spark-shell. 

import org.json4s._
import org.json4s.native.JsonMethods._
parse(""" { "numbers" : [1, 2, 3, 4] } """)

(with org.json4s.native dependency added to both Zeppelin and Spark-shell)

**Comment by Leemoonsoo** [comment]
I've pushed a fix to branch new/depinterpreter #319 

![image](https://cloud.githubusercontent.com/assets/1540981/6137355/808ad2ec-b1bb-11e4-8845-3bc6c5b4b914.png)

**Comment by swkimme** [comment]
json4s is now OK but another error pop up.

java.lang.NoClassDefFoundError: com/thoughtworks/paranamer/Paranamer
	at org.json4s.Extraction$.extract(Extraction.scala:330)
	at org.json4s.Extraction$.extract(Extraction.scala:42)
	at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
	at org.json4s.native.Serialization$.read(Serialization.scala:72)
	at io.prediction.data.storage.hbase.HBEventsUtil$$anonfun$7.apply(HBEventsUtil.scala:241)
	at io.prediction.data.storage.hbase.HBEventsUtil$$anonfun$7.apply(HBEventsUtil.scala:241)
	at scala.Option.map(Option.scala:145)
	at io.prediction.data.storage.hbase.HBEventsUtil$.resultToEvent(HBEventsUtil.scala:241)
	at $line39.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$anonfun$1.apply(<console>:44)
	at $line39.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$anonfun$1.apply(<console>:42)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1220)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:904)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:904)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1143)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1143)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:62)
	at org.apache.spark.scheduler.Task.run(Task.scala:54)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.thoughtworks.paranamer.Paranamer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

And I'm not sure this kind of class loading issue is making zeppelin too much fragile and unstable. 
We may need another approach to this problem..

**Comment by Leemoonsoo** [comment]
I tried with PredictionIO

I imported dependencies
```
%dep
z.reset
z.addRepo("Sonatype snapshot").url("https://oss.sonatype.org/content/repositories/snapshots").snapshot
z.load("io.prediction::core:0.8.6").exclude("org.mongodb:*")
z.load("io.prediction::data:0.8.6").exclude("org.mongodb:*")
z.load("eu.unicredit::hbase-rdd:0.4.0-SNAPSHOT")
```

and i could access hbase data from Zeppelin without classloading error.
Could you instruct me to reproduce the error?

**Comment by swkimme** [comment]
I can access the data too, 
but got error while parsing the result.

Plz try this code.
```
import unicredit.spark.hbase._
import io.prediction.data.storage.hbase._

case class Config(
  quorum: String,
  rootdir: String
)
val c = Config("localhost", "file:///var/lib/hbase")
implicit val config = HBaseConfig(c)

val table = "predictionio_eventdata:events_1"

import org.apache.hadoop.hbase.client.Result
import org.joda.time.DateTime
import org.joda.time.DateTimeZone

import org.apache.hadoop.hbase.mapreduce.TableInputFormat
import org.apache.hadoop.hbase.io.ImmutableBytesWritable

def makeConf(config: HBaseConfig, table: String) = {
  val conf = config.get
  conf.set(TableInputFormat.INPUT_TABLE, table)
  conf
}

val eventRdd2 = sc.newAPIHadoopRDD(makeConf(config, table), classOf[TableInputFormat],
  classOf[ImmutableBytesWritable], classOf[Result]) map {
  case (key, result) => 
  HBEventsUtil.resultToEvent(result, 1)
}
eventRdd2.count

```

**Comment by dszeto** [comment]
Not sure if this is related. When I pulled 2d027aa34a3e120e03c53bc741b5266dbafc0633 today and try to read the same Parquet file from HDFS again, I hit the following (it used to work before I pull)

```
val rdd = sqlc.parquetFile("hdfs://server/foobar.par")

java.lang.NoClassDefFoundError: Could not initialize class org.json4s.jackson.JsonMethods$
at org.apache.spark.sql.catalyst.types.DataType$.fromJson(dataTypes.scala:40)
at org.apache.spark.sql.parquet.ParquetTypesConverter$$anonfun$5.apply(ParquetTypes.scala:368)
at org.apache.spark.sql.parquet.ParquetTypesConverter$$anonfun$5.apply(ParquetTypes.scala:368)
at scala.util.Try$.apply(Try.scala:161)
at org.apache.spark.sql.parquet.ParquetTypesConverter$.convertFromString(ParquetTypes.scala:368)
at org.apache.spark.sql.parquet.ParquetTypesConverter$.readSchemaFromFile(ParquetTypes.scala:481)
at org.apache.spark.sql.parquet.ParquetRelation.<init>(ParquetRelation.scala:65)
at org.apache.spark.sql.SQLContext.parquetFile(SQLContext.scala:165)
at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:17)
at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:22)
at $iwC$$iwC$$iwC$$iwC.<init>(<console>:24)
at $iwC$$iwC$$iwC.<init>(<console>:26)
at $iwC$$iwC.<init>(<console>:28)
at $iwC.<init>(<console>:30)
at <init>(<console>:32)
at .<init>(<console>:36)
at .<clinit>(<console>)
at .<init>(<console>:7)
at .<clinit>(<console>)
at $print(<console>)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:852)
at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1125)
at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:674)
at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:705)
at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:669)
at com.nflabs.zeppelin.spark.SparkInterpreter.interpretInput(SparkInterpreter.java:482)
at com.nflabs.zeppelin.spark.SparkInterpreter.interpret(SparkInterpreter.java:458)
at com.nflabs.zeppelin.spark.SparkInterpreter.interpret(SparkInterpreter.java:452)
at com.nflabs.zeppelin.interpreter.ClassloaderInterpreter.interpret(ClassloaderInterpreter.java:54)
at com.nflabs.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:77)
at com.nflabs.zeppelin.notebook.Paragraph.jobRun(Paragraph.java:184)
at com.nflabs.zeppelin.scheduler.Job.run(Job.java:147)
at com.nflabs.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:85)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by swkimme** [comment]
@dszeto 
Looks very similar. 
Plz continue try with the settings before you pulled commit for now..

The dependency class loading is totally messy for now, we have different approach.
We're going to divide interpreter into a different process, then we're able to minimize dependency included in interpreter.
We believe this approach will remove or reduce class loading issues.

**Comment by dszeto** [comment]
Sure. I'll keep this thread on my radar for now. Thanks!

**Comment by veve90** [comment]
Hello,

I just started to use zeppelin, but there is no much in the tutorials... could you please indicate me how I can load data from hbase? 

Thank you!

**Comment by swkimme** [comment]
@veve90 
Hi, 
You can use the codes above. 
```
%dep
z.reset
z.addRepo("Sonatype snapshot").url("https://oss.sonatype.org/content/repositories/snapshots").snapshot
z.load("io.prediction::core:0.8.6").exclude("org.mongodb:*")
z.load("io.prediction::data:0.8.6").exclude("org.mongodb:*")
z.load("eu.unicredit::hbase-rdd:0.4.0-SNAPSHOT")

```

```
import unicredit.spark.hbase._
import io.prediction.data.storage.hbase._

case class Config(
  quorum: String,
  rootdir: String
)
val c = Config("localhost", "file:///var/lib/hbase")
implicit val config = HBaseConfig(c)

val table = "predictionio_eventdata:events_1"

import org.apache.hadoop.hbase.client.Result
import org.joda.time.DateTime
import org.joda.time.DateTimeZone

import org.apache.hadoop.hbase.mapreduce.TableInputFormat
import org.apache.hadoop.hbase.io.ImmutableBytesWritable

def makeConf(config: HBaseConfig, table: String) = {
  val conf = config.get
  conf.set(TableInputFormat.INPUT_TABLE, table)
  conf
}

val eventRdd2 = sc.newAPIHadoopRDD(makeConf(config, table), classOf[TableInputFormat],
  classOf[ImmutableBytesWritable], classOf[Result]) map {
  case (key, result) => 
  HBEventsUtil.resultToEvent(result, 1)
}
eventRdd2.count

```

But there are some issues running this codes, 
You'll need to use 
https://github.com/NFLabs/zeppelin/pull/364
this branch. (unstable yet, tough)

**Comment by veve90** [comment]
Thank you @swkimme !

when I try to import the used libraries I get:

    get error: not found: value unicredit
           import unicredit.spark.hbase._

do I have to download the libraries manually and add them as jars? What should I do?

thank you!

**Comment by swkimme** [comment]
@veve90 
You can use 
```
%dep
z.reset
z.addRepo("Sonatype snapshot").url("https://oss.sonatype.org/content/repositories/snapshots").snapshot
z.load("io.prediction::core:0.8.6").exclude("org.mongodb:*")
z.load("io.prediction::data:0.8.6").exclude("org.mongodb:*")
z.load("eu.unicredit::hbase-rdd:0.4.0-SNAPSHOT")

```
this to download and load jar. 
You need to run it before running other paragraph.
(Interpreter menu -> restart interpreter -> start %dep first)
This feature is quite new, we don't have proper doc yet..

**Comment by veve90** [comment]
Thank you! Now I don't get any result (so I think that the table is not really accessed)

In the line
val table = "predictionio_eventdata:events_1"

what is predictionio_eventdata? 

I'm using Cloudera and for HBase I don"t see any domain/database name for my hbase tables...

Thank you!

**Comment by swkimme** [comment]
@veve90 
It was test codes for integrating Prediction IO with Zeppelin, 
you may replace ```predictionio_eventdata:events_1 ``` to your table name. 

Also you may need to provide proper configs, 
```val c = Config("localhost", "file:///var/lib/hbase")```

**Comment by veve90** [comment]
I replaced the `val c = Config("localhost", "file:///var/lib/hbase")` with my config and the table with my event table but there is no result. 

I tried to replace my table name with a wrong table name but nothing... (no answer)
Where can I search for more information? 

I also tried to do a query from shell
    %sh
    hive -e "select count(*) from myTable"

but there is no result, the  interpreter is not finishing the query in 10 mintes (in the real shell that is present on the same machine, it finishes in less than 2 minutes)...


In the logs the only strage error is :
`
({main} AbstractLifeCycle.java[setFailed]:204) - FAILED SocketConnector@0.0.0.0:8080: java.net.BindException: Address already in use
java.net.BindException: Address already in use
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)
        at java.net.ServerSocket.bind(ServerSocket.java:376)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at java.net.ServerSocket.<init>(ServerSocket.java:181)
        at org.eclipse.jetty.server.bio.SocketConnector.newServerSocket(SocketConnector.java:96)
        at org.eclipse.jetty.server.bio.SocketConnector.open(SocketConnector.java:85)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
        at org.eclipse.jetty.server.bio.SocketConnector.doStart(SocketConnector.java:156)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.Server.doStart(Server.java:293)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at com.nflabs.zeppelin.server.ZeppelinServer.main(ZeppelinServer.java:82)
 WARN [2015-03-09 11:12:51,499] ({main} AbstractLifeCycle.java[setFailed]:204) - FAILED org.eclipse.jetty.server.Server@1e8e9308: java.net.BindException: Address already in use
java.net.BindException: Address already in use
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)
        at java.net.ServerSocket.bind(ServerSocket.java:376)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at java.net.ServerSocket.<init>(ServerSocket.java:181)
        at org.eclipse.jetty.server.bio.SocketConnector.newServerSocket(SocketConnector.java:96)
        at org.eclipse.jetty.server.bio.SocketConnector.open(SocketConnector.java:85)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
        at org.eclipse.jetty.server.bio.SocketConnector.doStart(SocketConnector.java:156)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.Server.doStart(Server.java:293)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at com.nflabs.zeppelin.server.ZeppelinServer.main(ZeppelinServer.java:82)
`

I have the feeling that the code is not executed....

**Comment by swkimme** [comment]
Are you able to run simple codes, like ```val a = 1```?

**Comment by veve90** [comment]
yes I can do simple codes like the one that you gave as an example ...

**Comment by swkimme** [comment]
@veve90 
Can you try and paste here the result of simpler codes?
like, 
```
val eventRdd2 = sc.newAPIHadoopRDD(makeConf(config, table), classOf[TableInputFormat],
  classOf[ImmutableBytesWritable], classOf[Result]) map {
  case (key, result) => result
}
eventRdd2.count
```

And also I recommend to try same codes in spark-shell first, if Zeppelin seems not working well.
