### ISSUE TITLE
Got exception while running some codes after loading dependency with %dep

### ISSUE THREAD

**Issue by swkimme** [NFLabs/zeppelin#339]
Code is like 

  val dailyStats = createRDDFromSparkResult(name="daily_stats").map(DailyStatsChartBuilder.fromCsv(_))
  dailyStats.registerTempTable("daily_stats")

exception: 

scala.reflect.internal.MissingRequirementError: class org.apache.spark.sql.catalyst.ScalaReflection in JavaMirror with sun.misc.Launcher$AppClassLoader@29578426 of type class sun.misc.Launcher$AppClassLoader with classpath [file:/home/zeppelin/zeppelin/,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/javax.ws.rs-api-2.0-m10.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jetty-jsp-8.1.14.v20131031.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jackson-module-jsonSchema-2.1.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/javax.servlet.jsp-2.2.0.v201112011158.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/swagger-jersey-jaxrs_2.10-1.3.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/geronimo-javamail_1.4_spec-1.7.1.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jsr311-api-1.1.1.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/dom4j-1.6.1.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/commons-logging-1.1.1.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/wsdl4j-1.6.3.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/cxf-rt-core-2.7.7.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/joda-convert-1.6.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/scala-compiler-2.10.4.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/swagger-annotations_2.10-1.3.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jersey-multipart-1.13.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jetty-all-server-8.1.14.v20131031.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/asm-3.1.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/cxf-rt-frontend-jaxrs-2.7.7.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/json4s-native_2.10-3.2.10.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/swagger-core_2.10-1.3.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/scala-reflect-2.10.4.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/org.eclipse.jdt.core-3.7.1.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/joda-time-2.3.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/c3p0-0.9.1.1.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/swagger-jaxrs_2.10-1.3.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jersey-servlet-1.18.1.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/log4j-1.2.17.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/Java-WebSocket-1.3.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jackson-jaxrs-json-provider-2.0.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jackson-module-jaxb-annotations-2.0.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/slf4j-log4j12-1.7.5.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/json4s-ext_2.10-3.2.10.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/gson-2.1.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/scalap-2.10.4.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/commons-lang-2.5.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/atmosphere-runtime-2.2.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/scala-library-2.10.4.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/javax.annotation-1.1.0.v201108011116.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/cxf-rt-transports-http-2.7.7.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jaxb-impl-2.2.6.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/guava-15.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/geronimo-servlet_3.0_spec-1.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/javax.el-2.2.0.v201108011116.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jersey-client-1.9.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/slf4j-api-1.7.5.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jersey-core-1.9.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/json4s-core_2.10-3.2.10.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/com.sun.el-2.2.0.v201108011116.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/javax.activation-1.1.0.v201105071233.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/reflections-0.9.8.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/cxf-api-2.7.7.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/javax.servlet-3.0.0.v201112011016.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/zeppelin-zengine-0.5.0-SNAPSHOT.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/cxf-rt-transports-http-jetty-2.7.7.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/json4s-jackson_2.10-3.2.10.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/stax2-api-3.1.1.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/atmosphere-annotations-2.2.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/javax.security.auth.message-1.0.0.v201108011116.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/commons-configuration-1.9.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/atmosphere-jersey-2.2.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/commons-io-2.4.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/xmlschema-core-2.0.3.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/javax.mail.glassfish-1.4.1.v201005082020.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/json4s-ast_2.10-3.2.10.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/jersey-server-1.9.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/cxf-rt-bindings-xml-2.7.7.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/woodstox-core-asl-4.2.0.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/mimepull-1.6.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/quartz-2.2.1.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar,file:/home/zeppelin/zeppelin/zeppelin-server/target/lib/javassist-3.12.1.GA.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/dom4j-1.6.1.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/commons-logging-1.1.1.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/c3p0-0.9.1.1.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/log4j-1.2.17.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/slf4j-log4j12-1.7.5.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/gson-2.1.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/commons-lang-2.5.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/guava-15.0.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/xml-apis-1.4.01.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/slf4j-api-1.7.5.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/reflections-0.9.8.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/commons-configuration-1.9.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/commons-io-2.4.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/quartz-2.2.1.jar,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/lib/javassist-3.12.1.GA.jar,file:/home/zeppelin/zeppelin/,file:/home/zeppelin/zeppelin/conf/,file:/home/zeppelin/zeppelin/zeppelin-zengine/target/classes/,file:/home/zeppelin/zeppelin/zeppelin-server/target/classes/] and parent being sun.misc.Launcher$ExtClassLoader@30a4effe of type class sun.misc.Launcher$ExtClassLoader with classpath [file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/sunpkcs11.jar,file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/dnsns.jar,file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/localedata.jar,file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/sunjce_provider.jar,file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/zipfs.jar,file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/sunec.jar] and parent being primordial classloader with boot classpath [/usr/lib/jvm/java-7-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-7-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-7-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-7-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-7-oracle/jre/classes] not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.staticModuleOrClass(Mirrors.scala:72)
	at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:119)
	at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:21)
	at org.apache.spark.sql.catalyst.ScalaReflection$$typecreator1$1.apply(ScalaReflection.scala:115)
	at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe$lzycompute(TypeTags.scala:231)
	at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe(TypeTags.scala:231)
	at scala.reflect.api.TypeTags$class.typeOf(TypeTags.scala:335)
	at scala.reflect.api.Universe.typeOf(Universe.scala:59)
	at org.apache.spark.sql.catalyst.ScalaReflection$class.schemaFor(ScalaReflection.scala:115)
	at org.apache.spark.sql.catalyst.ScalaReflection$.schemaFor(ScalaReflection.scala:33)
	at org.apache.spark.sql.catalyst.ScalaReflection$class.schemaFor(ScalaReflection.scala:100)
	at org.apache.spark.sql.catalyst.ScalaReflection$.schemaFor(ScalaReflection.scala:33)
	at org.apache.spark.sql.catalyst.ScalaReflection$class.attributesFor(ScalaReflection.scala:94)
	at org.apache.spark.sql.catalyst.ScalaReflection$.attributesFor(ScalaReflection.scala:33)
	at org.apache.spark.sql.SQLContext.createSchemaRDD(SQLContext.scala:111)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.loadDailyStats(<console>:55)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:57)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:62)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:64)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:66)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:68)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:70)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:72)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:74)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:76)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:78)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:80)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:82)
	at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:84)
	at $iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:86)
	at $iwC$$iwC$$iwC$$iwC.<init>(<console>:88)
	at $iwC$$iwC$$iwC.<init>(<console>:90)
	at $iwC$$iwC.<init>(<console>:92)
	at $iwC.<init>(<console>:94)
	at <init>(<console>:96)
	at .<init>(<console>:100)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:852)
	at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1125)
	at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:674)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:705)
	at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:669)
	at com.nflabs.zeppelin.spark.SparkInterpreter.interpretInput(SparkInterpreter.java:482)
	at com.nflabs.zeppelin.spark.SparkInterpreter.interpret(SparkInterpreter.java:458)
	at com.nflabs.zeppelin.spark.SparkInterpreter.interpret(SparkInterpreter.java:452)
	at com.nflabs.zeppelin.interpreter.ClassloaderInterpreter.interpret(ClassloaderInterpreter.java:54)
	at com.nflabs.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:77)
	at com.nflabs.zeppelin.notebook.Paragraph.jobRun(Paragraph.java:184)
	at com.nflabs.zeppelin.scheduler.Job.run(Job.java:147)
	at com.nflabs.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by swkimme** [comment]
Found problem reproduce with spark 1.2.1, changed title

**Comment by hunglin** [comment]
got the same error message

**Comment by hunglin** [comment]
https://github.com/NFLabs/zeppelin/pull/342

**Comment by Leemoonsoo** [comment]
@hunglin Thanks for the solution. 

Zeppelin want to keep separate classloader per Interpreter implementation to avoid dependency conflictions, so #342 is not the final solution i guess.

But I think it's a good solution for people those who a) uses Spark interpreter without using 3rd party interpreter, b) need a fix right now.

**Comment by swkimme** [comment]
@Leemoonsoo 
Then do we merge #342 or not?

**Comment by swkimme** [comment]
@hunglin 
I tried to apply your solution, I could register table but I got NoClassDefFoundException while running SparkSQL query. (with the case classes I've defined) 
Do you have no problem on it?

**Comment by hunglin** [comment]
Kevin, I don't have the problem.  Here are my steps:

mvn clean install -DskipTests -Pspark-1.2
bin/zeppelin.sh
go to localhost:8080, create a notebook and fun the following codes:

val bankText = sc.textFile("some_path/bank-full.csv")
case class Bank(age:Integer, job:String, marital : String, education :
String, balance : Integer)
val bank = bankText.map(s=>s.split(";")).filter(s=>s(0)!="\"age\"").map(
    s=>Bank(s(0).toInt,
            s(1).replaceAll("\"", ""),
            s(2).replaceAll("\"", ""),
            s(3).replaceAll("\"", ""),
            s(5).replaceAll("\"", "").toInt
        )
)
bank.registerTempTable("bank")
%sql select age, AVG(balance) from bank where age >=${minAge=0} AND age <=
${maxAge=100} group by age order by age

And I can see the result and charts.


Do you know why SparkInterpreter can load jars in interpreter/spark/
dynamically in spark 1.1.1 but not in spark 1.2?  I'm trying to figure out
the root cause of the issue but still missing some pieces.





Best,
Hung

**Comment by swkimme** [comment]
@hunglin 
Good to hear you're not getting the problem.

For me, the problem appears when dataset is large. (don't know why, tough)

**Comment by ricdong** [comment]
hello, 

I also have this issue in spark-1.2.0 which compiled with JDK1.7 when register a temp table. 

any suggestion?

**Comment by Leemoonsoo** [comment]
#364 with 'fork' option designed to fix the problem `scala.reflect.internal.MissingRequirementError: class org.apache.spark.sql.catalyst.ScalaReflection in JavaMirror with sun.misc.Launcher$AppClassLoader@29578426 of type class`
in spark-1.2.1
