### ISSUE TITLE
CDH5.3 spark 1.2.1 issue with Zeppelin

### ISSUE THREAD

**Issue by manasdebashiskar** [NFLabs/zeppelin#368]
Hi, 
 I am trying to make zeppelin work with my CDH5.3 (default spark1.2.1 ).
 I can get zeppelin started.
works
-------
sc.version
res0: String = 1.2.1 

Does not work for a file in my cluster.
-----------------------------------------------
val file = z.sc.textFile("hdfs://datanode01/data/grid") 

file.count
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 2.0 failed 4 times, most recent failure: Lost task 1.3 in stage 2.0 (TID 15, datanode05): java.lang.ClassCastException: org.apache.hadoop.mapred.JobConf cannot be cast to org.apache.spark.rdd.RDD
	at org.apache.spark.SparkContext$$anonfun$27.apply(SparkContext.scala:1050)
	at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:170)
	at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:170)
	at scala.Option.map(Option.scala:145)
	at org.apache.spark.rdd.HadoopRDD.getJobConf(HadoopRDD.scala:170)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.<init>(HadoopRDD.scala:214)
	at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:210)
	at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:99)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
	at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1214)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1203)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1202)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1202)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:696)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1420)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor.aroundReceive(DAGScheduler.scala:1375)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by swkimme** [comment]
Hi, how did you build Zeppelin?
Did you entered proper options for your spark package?? like,
mvn clean package -Pspark-1.2 -Dhadoop.version=2.5.0-cdh5.3.0 -Phadoop-2.4 -DskipTests

**Comment by manasdebashiskar** [comment]
Hi @swkimme,
 I used the exact command 
mvn clean package -Pspark-1.2 -Dhadoop.version=2.5.0-cdh5.3.0 -Phadoop-2.4 -DskipTests on my Centos 6.6 machine to build it.

Anything else I can look at to give me some clue?

**Comment by manasdebashiskar** [comment]
Also, 
 My spark cluster is a stand alone and not the yarn based. Could that be playing a role?

**Comment by swkimme** [comment]
Standalone is not a problem, 
I guess you've not configured external Spark cluster, using spark local mode inside Zeppelin. Right?
It's very strange that Zeppelin is casting JobConf into RDD..

**Comment by manasdebashiskar** [comment]
Hi @swkimme, 
 I should have given you more detail. 
 I do have a 6 machines spark cluster with CDH5.3(Centos 6.6 machine containing spark 1.2.1)
 I checkedout zeppelin to my driver node and built it with 
mvn clean package -Pspark-1.2 -Dhadoop.version=2.5.0-cdh5.3.0 -Phadoop-2.4 -DskipTests option.
The only two configuration changes are in zeppelin.env.sh that are the MASTER and JAVA_HOME.
My cluster is a stand alone and works fine with my spark jars. I am using HDFS as my file system.

Please let me know if you need more info.

..Manas

**Comment by swkimme** [comment]
First, I recommend you to try with local mode, just comment out MASTER env. 
(It should work in my thought) 

The problem you're facing is likely from the mismatch of spark build from Zeppelin and your cluster. 
As a workaround you can try ```rm zeppelin/interpreter/spark/*spark*.jar ``` and copy your spark jar into ```zeppelin/interpreter/spark/```.

Also we're trying some ideas to fix this kind of problem.
Cheers!

**Comment by manasdebashiskar** [comment]
Thanks @swkimme, 
I dropped the one jar that Cloudera has. Seems the build did not fetch the right dependencies after all.

..Manas

**Comment by worwornf** [comment]
http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/cdh_rn_spark_ic.html
at the bottom of this link 
'The CDH 5.3 version of Spark 1.2 differs from the Apache Spark 1.2 release in using Akka version 2.2.3, the version used by Spark 1.1 and CDH 5.2. Apache Spark 1.2 uses Akka version 2.3.4.'
I think it can make some problems.
We also had some troubles because of the different akka version between CDH spark and zeppelin.

**Comment by ZhijieWang** [comment]
Confirmed, it was also discussed here repo. https://github.com/spark-jobserver/spark-jobserver/issues/60. I used all native spark, hadoop and yarn and still no luck.

**Comment by H4ml3t** [comment]
Same problem here,
built with: 
```mvn clean package -Pspark-1.2 -Dhadoop.version=2.5.0-cdh5.3.1 -Phadoop-2.4 -Pyarn -DskipTests```

I'm using a cluster and an outside node running zeppeling in yarn-client mode.

```
java.lang.ClassCastException: org.apache.hadoop.mapred.JobConf cannot be cast to org.apache.spark.rdd.RDD
```

Any suggestion?

**Comment by H4ml3t** [comment]
Please VOTE for this issue here in Jira:

https://issues.apache.org/jira/browse/ZEPPELIN-246?jql=project%20%3D%20ZEPPELIN%20AND%20resolution%20%3D%20Unresolved%20AND%20priority%20%3D%20Major%20ORDER%20BY%20key%20DESC
