### ISSUE TITLE
Zeppelin not starting. NoSuchMethodError

### ISSUE THREAD

**Issue by wienczny** [NFLabs/zeppelin#407]
Hi,

I checked out the latest git and followed the guide. I ran into #403. When the fix from that report was applied and I ran
```
./bin/zeppelin-daemon.sh start
```
I got 
```
Exception in thread "main" java.lang.NoSuchMethodError: org.eclipse.jetty.webapp.WebAppContext.setProtectedTargets([Ljava/lang/String;)V
        at org.eclipse.jetty.webapp.WebAppContext.<init>(WebAppContext.java:198)
        at com.nflabs.zeppelin.server.ZeppelinServer.setupWebAppContext(ZeppelinServer.java:236)
        at com.nflabs.zeppelin.server.ZeppelinServer.main(ZeppelinServer.java:73)
```
in my logfile.

**Comment by seckin206** [comment]
Can you provide your build configuration?

**Comment by wienczny** [comment]
Git commit apache/incubator-zeppelin@2498e5df12ae8cc1b24375e253df94394710aaf8
```
$ mvn -version
Apache Maven 3.3.1 (NON-CANONICAL_2015-03-18T18:27:34_root; 2015-03-18T16:27:34+01:00)
Maven home: /opt/maven
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-jdk/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "3.19.2-1-arch", arch: "amd64", family: "unix"
```
Commands used:
```
mvn clean package
./bin/zeppelin-daemon.sh start
```

**Comment by seckin206** [comment]
Could you provide your full log of build? I couldn't replicate the behaviour so far.

**Comment by wienczny** [comment]
[build.log](https://gist.github.com/8386ef55a9feaab84180.git)

**Comment by seckin206** [comment]
First of all, it's not related to #403, since there is no problem with frontend-plugin. Could you debug your application and put debug logs here?

**Comment by wienczny** [comment]
When linking to the other bug, I just wanted to say, that I had to change the plugin dependency. This change was not yet in the repo.
When debugging there is a difference between IDE and remote debugging. Remote debugging fails when calling ContextHandler#setProtectedDomains. Some dependency must be wrong here.
Could this be somehow related to https://github.com/hawtio/hawtio/issues/122#issuecomment-13922038 ?
